package com.adrian.ake.sistemabibliotecario.models;
// Generated 17/01/2018 08:36:31 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Anaquel generated by hbm2java
 */
public class Anaquel  implements java.io.Serializable {


     private int idanaquel;
     private Boolean activo;
     private Date createdAt;
     private Date updatedAt;
     private Set libros = new HashSet(0);

    public Anaquel() {
    }

	
    public Anaquel(int idanaquel) {
        this.idanaquel = idanaquel;
    }
    public Anaquel(int idanaquel, Boolean activo, Date createdAt, Date updatedAt, Set libros) {
       this.idanaquel = idanaquel;
       this.activo = activo;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.libros = libros;
    }
   
    public int getIdanaquel() {
        return this.idanaquel;
    }
    
    public void setIdanaquel(int idanaquel) {
        this.idanaquel = idanaquel;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }




}


