package com.adrian.ake.sistemabibliotecario.models;
// Generated 17/01/2018 08:36:31 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private Integer idautor;
     private Nacionalidad nacionalidad;
     private String nombres;
     private String apellidos;
     private Date createdAt;
     private Date updatedAt;
     private Set libros = new HashSet(0);

    public Autor() {
    }

	
    public Autor(Nacionalidad nacionalidad, String nombres, String apellidos) {
        this.nacionalidad = nacionalidad;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Autor(Nacionalidad nacionalidad, String nombres, String apellidos, Date createdAt, Date updatedAt, Set libros) {
       this.nacionalidad = nacionalidad;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.libros = libros;
    }
   
    public Integer getIdautor() {
        return this.idautor;
    }
    
    public void setIdautor(Integer idautor) {
        this.idautor = idautor;
    }
    public Nacionalidad getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(Nacionalidad nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }




}


