package com.adrian.ake.sistemabibliotecario.models;
// Generated 17/01/2018 08:36:31 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private String idlibro;
     private Anaquel anaquel;
     private Autor autor;
     private Editorial editorial;
     private String titulo;
     private String descripcion;
     private Integer mesPublicacion;
     private Integer anioPublicacion;
     private Boolean activo;
     private Date createdAt;
     private Date updatedAt;

    public Libro() {
    }

	
    public Libro(String idlibro, Anaquel anaquel, Autor autor, Editorial editorial, String titulo, String descripcion) {
        this.idlibro = idlibro;
        this.anaquel = anaquel;
        this.autor = autor;
        this.editorial = editorial;
        this.titulo = titulo;
        this.descripcion = descripcion;
    }
    public Libro(String idlibro, Anaquel anaquel, Autor autor, Editorial editorial, String titulo, String descripcion, Integer mesPublicacion, Integer anioPublicacion, Boolean activo, Date createdAt, Date updatedAt) {
       this.idlibro = idlibro;
       this.anaquel = anaquel;
       this.autor = autor;
       this.editorial = editorial;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.mesPublicacion = mesPublicacion;
       this.anioPublicacion = anioPublicacion;
       this.activo = activo;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public String getIdlibro() {
        return this.idlibro;
    }
    
    public void setIdlibro(String idlibro) {
        this.idlibro = idlibro;
    }
    public Anaquel getAnaquel() {
        return this.anaquel;
    }
    
    public void setAnaquel(Anaquel anaquel) {
        this.anaquel = anaquel;
    }
    public Autor getAutor() {
        return this.autor;
    }
    
    public void setAutor(Autor autor) {
        this.autor = autor;
    }
    public Editorial getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(Editorial editorial) {
        this.editorial = editorial;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getMesPublicacion() {
        return this.mesPublicacion;
    }
    
    public void setMesPublicacion(Integer mesPublicacion) {
        this.mesPublicacion = mesPublicacion;
    }
    public Integer getAnioPublicacion() {
        return this.anioPublicacion;
    }
    
    public void setAnioPublicacion(Integer anioPublicacion) {
        this.anioPublicacion = anioPublicacion;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


